In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv(r"C:\Users\maana\OneDrive\文档\sql\spotify data\artists.csv")

# Save first 5000 rows
df.head(5000).to_csv("artists.csv", index=False)
df.head(5000)

,id,followers,genres,name,popularity
0,0DheY5irMjBUeLybbCUEZ2,0.0,[],Armid & Amir Zare Pashai feat. Sara Rouzbehani,0
1,0DlhY15l3wsrnlfGio2bjU,5.0,[],ปูนา ภาวิณี,0
2,0DmRESX2JknGPQyO15yxg7,0.0,[],Sadaa,0
3,0DmhnbHjm1qw6NCYPeZNgJ,0.0,[],Tra'gruda,0
4,0Dn11fWM7vHQ3rinvWEl4E,2.0,[],Ioannis Panoutsopoulos,0
...,...,...,...,...,...
4995,7Jp5Nw7cNZTkwFgJX06Cqk,361983.0,"['rap df', 'sertanejo pop']",Dan Lellis,58
4996,0kj68SnX4WCXwveyBbRX8p,29900.0,['funk bh'],MC Saci,55
4997,03lJxNYml1ArLjcZLxfIvz,2080285.0,"['sertanejo', 'sertanejo pop', 'sertanejo univ...",Paula Mattos,55
4998,3DAlQBPv5zWasPxV5Tr8ok,14159.0,[],Zerky,57
4999,2Ip2jiEjsSe8pmRBzwTv5N,47316.0,"['brazilian hip hop', 'grime brasileiro']",Febem,55

In [8]:
db = pd.read_csv(r"C:\Users\maana\OneDrive\文档\sql\spotify data\SpotifyFeatures.csv")

# Save first 5000 rows
db.head(5000).to_csv("spotify_features.csv", index=False)
db.head(5000)

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.6110,0.389,99373,0.910,0.000000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.2460,0.590,137373,0.737,0.000000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.9520,0.663,170267,0.131,0.000000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.7030,0.240,152427,0.326,0.000000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.9500,0.331,82625,0.225,0.123000,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Alternative,UMI,High School,2Q5l817bEwCulz8WjTqyvL,52,0.1050,0.837,133667,0.601,0.000012,A#,0.1020,-5.674,Major,0.0729,121.985,4/4,0.956
4996,Alternative,for KING & COUNTRY,Shoulders,5MCG4XcVcvCOXWpSg2cfRC,53,0.1710,0.518,303307,0.744,0.000008,D#,0.1090,-7.106,Major,0.0351,98.022,4/4,0.161
4997,Alternative,Queens of the Stone Age,Feet Don't Fail Me,2JB7PvDV0R3Vwbq0iy1WPe,57,0.0188,0.514,341825,0.806,0.002270,D,0.0976,-6.947,Major,0.0582,109.331,4/4,0.288
4998,Alternative,Atmosphere,The Best Day,1WPQ1MfGc8KYi4eu0JwjlR,52,0.3580,0.882,216893,0.624,0.000000,F#,0.0678,-5.372,Major,0.0681,96.897,4/4,0.900
4999,Alternative,Florence + The Machine,Big God,1NcXkWB3UwXfMt8izByICb,59,0.5280,0.625,241760,0.366,0.000021,D,0.0958,-8.388,Minor,0.0331,72.992,4/4,0.219

In [9]:
dt = pd.read_csv(r"C:\Users\maana\OneDrive\文档\sql\spotify data\tracks.csv")

# Save first 5000 rows
dt.head(5000).to_csv("tracks.csv", index=False)
dt.head(5000)

,id,name,popularity,duration_ms,explicit,artists,id_artists,release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,35iwgR4jXetI318WEWsa1Q,Carve,6,126903,0,['Uli'],['45tIt06XoI0Iio4LBEVpls'],22-02-1922,0.645,0.4450,0,-13.338,1,0.4510,0.674,0.7440,0.151,0.127,104.851,3
1,021ht4sdgPcrDgSk7JTbKY,Capítulo 2.16 - Banquero Anarquista,0,98200,0,['Fernando Pessoa'],['14jtPCOoNZwquk5wd9DxrY'],01-06-1922,0.695,0.2630,0,-22.136,1,0.9570,0.797,0.0000,0.148,0.655,102.009,1
2,07A5yehtSnoedViJAZkNnc,Vivo para Quererte - Remasterizado,0,181640,0,['Ignacio Corsini'],['5LiOoJbxVSAMkBS2fUm3X2'],21-03-1922,0.434,0.1770,1,-21.180,1,0.0512,0.994,0.0218,0.212,0.457,130.418,5
3,08FmqUhxtyLTn6pAh6bk45,El Prisionero - Remasterizado,0,176907,0,['Ignacio Corsini'],['5LiOoJbxVSAMkBS2fUm3X2'],21-03-1922,0.321,0.0946,7,-27.961,1,0.0504,0.995,0.9180,0.104,0.397,169.980,3
4,08y9GfoqCWfOGsKdwojr5e,Lady of the Evening,0,163080,0,['Dick Haymes'],['3BiJGZsyX9sJchTqcSA7Su'],1922,0.402,0.1580,3,-16.900,0,0.0390,0.989,0.1300,0.311,0.196,103.220,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1dWZCMwYq2c5WIh1ti5mgz,No Quiero Verla Más - Remasterizado,0,187493,0,"['Francisco Canaro', 'Charlo']","['2maQMqxNnlRrBrS1oAsrX9', '3Ry0Bx0jq7Z6nbzTfc...",05-11-1929,0.652,0.1490,7,-12.657,1,0.0590,0.994,0.8310,0.115,0.695,118.121,4
4996,1dxKJpiZmdvmIPzzcRLk24,"The Seasons, Op. 37a, TH 135: 10. October: Aut...",1,204867,0,"['Pyotr Ilyich Tchaikovsky', 'Vása Prihoda', '...","['3MKCzCnpzw3TjUYs2v7vDA', '7hETeZMNJLaWWLdd55...",01-01-1929,0.364,0.2520,2,-15.194,0,0.0555,0.985,0.5650,0.136,0.342,74.795,3
4997,1eHJ0HNzSVAC5xvC5fK2A2,En mi Rancho Hay Una Flor - Instrumental (Rema...,0,170107,0,['Francisco Canaro'],['2maQMqxNnlRrBrS1oAsrX9'],15-10-1929,0.556,0.2930,7,-7.554,1,0.0626,0.991,0.8800,0.122,0.926,163.296,3
4998,1eIrN38INCVanDji2pnsEj,Queja Melodiosa - Remasterizado,0,190000,0,"['Francisco Canaro', 'Charlo']","['2maQMqxNnlRrBrS1oAsrX9', '3Ry0Bx0jq7Z6nbzTfc...",06-11-1929,0.583,0.1670,6,-14.328,0,0.0525,0.993,0.8520,0.103,0.598,118.097,4
4999,1edSnJ9AVeZLq289IDBSFa,La del Soto del Parral - Instrumental (Remaste...,0,186000,0,['Francisco Canaro'],['2maQMqxNnlRrBrS1oAsrX9'],22-10-1929,0.635,0.2160,2,-11.319,1,0.1130,0.995,0.7430,0.127,0.860,181.206,4